# automation of macro generation for resonant ods tables
# This script reads a JSON file containing table definitions and generates SQL macros for each table.
# will work with any JSON file that has a similar structure to one used

import os
import json
import re

# --- CONFIGURATION ---
customer_name = 'serenia'
json_path = fr"/home/{customer_name}.json"
output_folder = fr"/home/{customer_name}"   

# --- RAW TABLE LIST ---
raw_table_names = """
EMAILPURGETEMP_VC
AWSDMS_APPLY_EXCEPTIONS_VC
DMS_DOCUMENT_PERMISSION_VC
DMS_DOCUMENT_REVISION_ACTIVITY_VC
DMS_DOCUMENT_REVISION_VC
DMS_DOCUMENT_VC
FLYWAY_SCHEMA_HISTORY_VC
HISTORY_APPLICATION_VC
HISTORY_LIFEPOLICY_VC
HISTORY_REQUIREMENT_VC
LIFE_ACCELERATED_UW_AUDIT_VC
LIFE_ACCELERATEDTRIAGE_VC
LIFE_ADDRESS_VC
LIFE_AGENTDATA_VC
LIFE_AGENTERRORDETAILS_VC
LIFE_AGENTERRORS_VC
LIFE_AGGREGATECEDED_VC
LIFE_AGGREGATERETAINED_VC
LIFE_AGENTREPORT_VC
LIFE_AMENDMENT_VC
LIFE_ANNUITY_VC
LIFE_APPLICATIONINFO_VC
LIFE_APPLICATIONINFO_ADDITIONAL_FIELDS_VC
LIFE_APPLICATIONINFO_TRACKING_IDS_VC
LIFE_ARRANGEMENT_VC
LIFE_ARRDESTINATION_VC
LIFE_ARRSOURCE_VC
LIFE_ARRTAXWITHHOLDING_VC
LIFE_AUTHORITY_VC
LIFE_AUTODECISION_VC
LIFE_AUTOUWLOG_VC
LIFE_BANKING_VC
LIFE_BANKRUPTCY_VC
LIFE_CASEMANAGER_VC
LIFE_CHANGESUBTYPE_VC
LIFE_CHATMESSAGE_VC
LIFE_CHECKINGREPORT_VC
LIFE_CHILDREN_VC
LIFE_CONTACT_VC
LIFE_COVERAGE_VC
LIFE_COVOPTION_VC
LIFE_CREDITINQUIRY_VC
LIFE_CREDITMODEL_VC
LIFE_CREDITMODELCODE_VC
LIFE_CREDITMODELREASON_VC
LIFE_CREDITREPORT_VC
LIFE_CRIMINALOFFENSE_VC
LIFE_CRIMINALRECORD_VC
LIFE_DECISIONREASONS_VC
LIFE_DISQUALIFIEDAUTOAPPROVALREASONS_VC
LIFE_DIEXCLUSIONS_VC
LIFE_DOC_REVISION_ACTIVITY_VC
LIFE_DOCUMENT_RESOURCE_VC
LIFE_DOCUMENT_REVISION_VC
LIFE_EIRINQUIRY_VC
LIFE_EMAIL_VC
LIFE_EMPLOYMENT_VC
LIFE_ENDORSEMENT_VC
LIFE_EXCLUSION_VC
LIFE_FAMILYILLNESS_VC
LIFE_FINANCIAL_ACTIVITY_VC
LIFE_FINANCIALEXP_VC
LIFE_FLFMEMBERSHIP_VC
LIFE_FORMDATA_VC
LIFE_FORMFIELDDEF_VC
LIFE_FORMRESPONSE_VC
LIFE_GENERIC_DOCUMENT_ARCHIVE_VC
LIFE_GENERIC_DOCUMENT_VC
LIFE_GIACTALERTMESSAGE_VC
LIFE_GIDENTITY_VC
LIFE_GROUPEDPARTY_VC
LIFE_GVERIFY_VC
LIFE_HEALTHPIQTURE_VC
LIFE_HEALTHPIQTURERISKSCORE_VC
LIFE_HOLIDAY_CALENDAR_VC
LIFE_IAIREPORT_VC
LIFE_IDENTITYVERIFICATION_VC
LIFE_IDENTITYVERIFMESSAGE_VC
LIFE_INSTANTID_VC
LIFE_INSTANTIDRISKCODE_VC
LIFE_INSURANCECOMPANY_VC
LIFE_INSTANTIDWATCHLIST_VC
LIFE_INSURED_VC
LIFE_INTEGRATIONMESSAGEDETAILS_VC
LIFE_INTEGRATIONMESSAGES_VC
LIFE_INTELRXORDER_VC
LIFE_IRIXMEDICALCLAIM_VC
LIFE_LABTESTING_VC
LIFE_LABTESTREMARK_VC
LIFE_LABTESTRESULT_VC
LIFE_LIFEPOLICY_VC
LIFE_LIFESTYLEACTIVITY_VC
LIFE_LINK_VC
LIFE_LINKEDPOLICIES_VC
LIFE_LINKMARKERS_VC
LIFE_LINKPOLICY_VC
LIFE_MEDCONDITION_VC
LIFE_MEDCONDITIONQUES_VC
LIFE_MEDICALEXAM_VC
LIFE_MEDTREATMENT_VC
LIFE_MIBFOLLOWUP_VC
LIFE_MIBINQUIRY_VC
LIFE_MVRINCIDENT_VC
LIFE_MVRINQUIRY_VC
LIFE_NCFINQUIRY_VC
LIFE_NIGO_VC
LIFE_NIGO2_VC
LIFE_NIGOLIST_VC
LIFE_NOTE_VC
LIFE_OTHERCOVERAGE_VC
LIFE_PARTICIPANT_VC
LIFE_PARTY_VC
LIFE_PARTY_ADDITIONAL_FIELDS_VC
LIFE_PARTYGROUP_VC
LIFE_PARTYREPORT_VC
LIFE_PARTYTRUSTEE_VC
LIFE_PASPRIORS_VC
LIFE_PAYOUT_VC
LIFE_PHONE_VC
LIFE_PHYSICIAN_VC
LIFE_PHYSICIANPARTY_VC
LIFE_POLICY_ADDITIONAL_FIELDS_VC
LIFE_POLICYAMENDMENTS_VC
LIFE_POLICYBENEFIT_VC
LIFE_POLICYHOLD
LIFE_PRIOR_VC
LIFE_PRIORCEDED_VC
LIFE_PRIORITY_SETTINGS_VC
LIFE_PRIORRETAINED_VC
LIFE_PRIORRIDERS_VC
LIFE_PRODUCER_VC
LIFE_QCERROR_VC
LIFE_QCREVIEW_VC
LIFE_QCREVIEWDETAIL_VC
LIFE_QCREVIEWDETAILNOTE_VC
LIFE_QCREVIEWNOTE_VC
LIFE_QUESTCHECK_VC
LIFE_QUESTCHECKLABTESTING_VC
LIFE_QUESTIONDETAIL_THRIVENT_VC
LIFE_QUESTIONDETAIL_VC
LIFE_QUEUED_DOCUMENT_VC
LIFE_REINSURANCE_0126_VC
LIFE_REINSURANCE_OLD_VC
LIFE_REINSURANCE_THRIVENT_VC
LIFE_REINSURANCE_THRIVENT0123_VC
LIFE_REINSURANCE_VC
LIFE_REINSURANCE0120_VC
LIFE_REINSURANCEQUOTES_OLD_VC
LIFE_REINSURANCEQUOTES_VC
LIFE_REINSURER_0126_VC
LIFE_REINSURER_THRIVENT_VC
LIFE_REINSURER_THRIVENT0123_VC
LIFE_REINSURER_VC
LIFE_REINSURER0120_VC
LIFE_REINSURERQUOTE_0126_VC
LIFE_REINSURERQUOTE_THRIVENT_VC
LIFE_REINSURERQUOTE_THRIVENT0123_VC
LIFE_REINSURERQUOTE_VC
LIFE_REINSURERQUOTE0120_VC
LIFE_RELATEDAPPLICATION_VC
LIFE_RELATEDPARTY_VC
LIFE_REPLACEMENTSUMMARY_VC
LIFE_REPLACEMENTSUMMARYINDEX_VC
LIFE_REPLACEMENTSUMMARYLOANDETAILS_VC
LIFE_REPORTMESSAGE_VC
LIFE_REQUIREMENTINFO_VC
LIFE_RFCASSIGNMENTS_VC
LIFE_RISK_VC
LIFE_RISKCLASSIFIER_VC
LIFE_RISKCLASSIFIERREASON_VC
LIFE_ROLLOVER_VC
LIFE_RXFILL_VC
LIFE_RXHISTORY_VC
LIFE_RXRULECLASS_VC
LIFE_RXRULEHIT_VC
LIFE_SCRIPTCHECKORDER_VC
LIFE_SCRIPTCHECKRXFILL_VC
LIFE_STATUSEVENT_VC
LIFE_SUBACCOUNT_VC
LIFE_SUBSTANCEUSAGE_VC
LIFE_SUITABILITY_VC
LIFE_TAX_WITHHOLDING_VC
LIFE_TEAM_ASSIGNMENT_VC
LIFE_TEAM_VC
LIFE_TEAMALLOCATION_VC
LIFE_TEAMDEF_VC
LIFE_TRACK_REASON_VC
LIFE_TRANSFER_SWITCH_VC
LIFE_TELEINTERVIEW_VC
LIFE_TELEINTERVIEWDETAIL_VC
LIFE_TRUERISK_VC
LIFE_TRUERISKCREDITTRADE_VC
LIFE_TRUERISKSCOREFACTOR_VC
LIFE_USERASSIGNMENT_VC
LIFE_USERAUTHORITY_VC
LIFE_USERLOG_VC
LIFE_UWASSESSMENT_VC
LIFE_UWASSIGNMENT_VC
LIFE_UWQUOTE_VC
LIFE_VIOLATION_VC
NOTIF_EVENT_EXTENSIONS_VC
PL_DATA_TABLES_VC
PL_DOC_REVISION_ACTIVITY_VC
PL_DOCUMENT_REVISION_VC
PL_DOCUMENT_VC
SYS_ACCESS_RIGHTS_EXT_VC
SYS_ACCESS_RIGHTS_VC
SYS_ACT_PARAM_VALUES_VC
SYS_ACTIVITIES_VC
SYS_APP_DATA_VC
SYS_AUDIT_LOG_VC
SYS_CHALLENGE_QUESTION_VC
SYS_COND_SPEC_VC
SYS_COUNTERS_VC
SYS_DOCUMENT_CONTENT_VC
SYS_EMAIL_ATTACHMENT_VC
SYS_EMAIL_DIRECTION_VC
SYS_EMAIL_PRIORITY_VC
SYS_EMAIL_QUEUE_ATTACHMENT_VC
SYS_EMAIL_QUEUE_VC
SYS_EMAIL_STATUS_VC
SYS_EMAIL_TEMPLATE_VC
SYS_EMAIL_VC
SYS_EVENT_VC
SYS_FORM_GENERATION_LOG_VC
SYS_FORM_TEMPLATE_VC
SYS_GUIDELINE_EVENTS_VC
SYS_INBOUND_LOG_VC
SYS_INBOUND_QUEUE_VC
SYS_JOB_DEFINITION_PARAMS_VC
SYS_JOB_DEFINITIONS_VC
SYS_JOB_RUNS_ARCHIVE_VC
SYS_JOB_RUNS_VC
SYS_JOB_SCHEDULE_PARAMS_VC
SYS_JOB_SCHEDULES_VC
SYS_LINK_EVENTS_VC
SYS_LOCKS_VC
SYS_LOGIN_RECORD_VC
SYS_MESSAGE_ERRORS_VC
SYS_MESSAGES_VC
SYS_NOTIFICATIONS_VC
SYS_OLD_PASSWORDS_VC
SYS_OUTBOUND_LOG_VC
SYS_POLLER_VC
SYS_POLLER_CONFIG_VC
SYS_POLLER_EVENT_VC
SYS_PROC_TIMERS_VC
SYS_PROCESS_APP_REFERENCE_VC
SYS_PROCESS_ROLE_USER_LOG_VC
SYS_PROCESS_ROLE_USER_VC
SYS_PROCESSES_VC
SYS_PROPERTY_VC
SYS_PROPERTY_VALUE_VC
SYS_REPORT_DESIGN_ROLE_VC
SYS_REPORT_DESIGN_VC
SYS_REPORT_FORMAT_VC
SYS_REPORT_FREQUENCY_VC
SYS_REPORT_RUN_LOG_VC
SYS_REQUIRED_ACTIVITIES_VC
SYS_RETAIN_USERS_VC
SYS_ROLE_DEFINITION_VC
SYS_ROLE_USER_MAP_VC
SYS_ROLES_VC
SYS_SCHEDULED_REPORT_VC
SYS_SERVICE_ACTIVITY_ARCHIVE_VC
SYS_SERVICE_ACTIVITY_LOG_VC
SYS_SERVICE_ACTIVITY_VC
SYS_SUB_PROPS_VC
SYS_SUBSCRIPTION_FILTERS_VC
SYS_SUBSCRIPTIONS_VC
SYS_SUSPENSIONS_VC
SYS_TIMERS_VC
SYS_TRACK_REASON_VC
SYS_USER_CHALLENGE_ANSWER_VC
SYS_TRACK_REASON_GUARDIAN_VC
SYS_USERS_VC
TEMP_USERLOOKUP_VC
TMP_AUDIT_ARCHIVE_LOG_VC
XPATHS_TO_BO_PROPS_VC
"""

# --- Normalize ---
target_tables = [
    re.sub(r'_v[a-z]*$', '', name.strip().lower())
    for name in raw_table_names.strip().splitlines()
]

# --- Load JSON ---
with open(json_path, "r") as f:
    all_tables_data = json.load(f)["TableList"]

# --- Format a column line ---
def format_column(col):
    name = col["Name"]
    col_type = col["Type"]
    alias = name.upper()
    return alias

# --- Make output folder ---
os.makedirs(output_folder, exist_ok=True)

# --- Generate SQL ---
for table_obj in all_tables_data:
    name = table_obj.get("Name", "").lower()
    if name not in target_tables:
        continue

    columns = table_obj.get("StorageDescriptor", {}).get("Columns", [])
    if not columns:
        continue

    formatted_cols = [format_column(col) for col in columns]

    # Format columns: first column no comma, others start with comma and aligned 8 spaces
    if len(formatted_cols) > 1:
        col_section = "\n        ," + "\n        ,".join(formatted_cols[1:])
    else:
        col_section = ""

    sql = f"""{{{{ config(
    schema='{customer_name}uw_ods',
    unique_key='ID',
) }}}}
with {name} as (
    select {formatted_cols[0]}{col_section}
        ,row_number() OVER (PARTITION BY ID ORDER BY COMMIT_TIMESTAMP DESC, TRANSACT_ID_SEQ DESC, TRANSACT_ID DESC) AS is_current
    from AwsDataCatalog.{{{{ ref('{customer_name}_intmd_{name}') }}}}

    {{% if is_incremental() %}}
    where commit_timestamp >= (select max(commit_timestamp) from AwsDataCatalog.{{{{ this }}}})
    {{% endif %}}
)

select * from {name} where is_current = 1"""

    output_path = os.path.join(output_folder, f"{customer_name}_{name}.sql")
    with open(output_path, "w") as f:
        f.write(sql)

print("SQL models generated successfully.")
